### ISSUE TITLE
Support for development versions of csharp-module

### ISSUE THREAD

**Issue by Rodhin** [emre1702/altv-CustomCommandsSystem#2]
Hi, the alt:V C# module got some major refactoring in the dev branch for the upcoming client-side module and now the "RegisterCustomCommands" extension does not work with the dev version of the module. IServer has been deprecated in favor of ICore. 

Could you please create a development version of your nuget package with support for the dev version of the C# module?

**Comment by emre1702** [comment]
Hey @Rodhin , sry for missing this Input. Will modify my notifications to get a mail on new issues.
You can now use[1.3.6-dev](https://www.nuget.org/packages/altV-CustomCommandsSystem/1.3.6-dev).

**Comment by Rodhin** [comment]
Thank you for the update :)
